### ISSUE TITLE
Cannot draw points when reproducing demo/index2.html

### ISSUE THREAD

**Issue by TianxiaoNYU** [gherardovarando/leaflet-csvtiles#1]
Hi! I would like to use csvtiles to deal with my own dataset, so I firstly attempted to reproduce both two demo. Unfortunately, I cannot draw any point in the map, while other functions like drawing grid works fine. 

I'm using the same js files as in the demo (Papa Parse v4.1.2, Leaflet 1.4.0), and I've downloaded the same csv files, too. But here it gives the error:
<img width="1373" alt="Screen Shot" src="https://user-images.githubusercontent.com/43696261/63038141-87884900-be8e-11e9-8e65-09db5bb5e129.png">

I've also tried the lastest Papa Parse v5.0.2, which indeed stopped this error, but still unable to draw points. It gives NaN in lng&lat for every point. 
<img width="1373" alt="Screen Shot 2019-08-14 at 12 30 46 PM" src="https://user-images.githubusercontent.com/43696261/63038542-62480a80-be8f-11e9-94ea-5da6e7041473.png">
I don't know why this happens; maybe there are some mistakes for my input/setting files or others that I didn't notice. Hope you can help figure that out! Thank you very much.

Here are all my files:
[csvtiles_files.zip](https://github.com/gherardovarando/leaflet-csvtiles/files/3502331/csvtiles_files.zip)

**Comment by gherardovarando** [comment]
Hi, are you trying to replicate the example locally ?

**Comment by gherardovarando** [comment]
Hi, I updated leaflet-csvtiles (0.5.0) to use PapaParse v5.1.1, now both examples should work. 
If you want to reproduce the example locally you should first serve the folder with a local server (e.g. `python -m http.server`) .
